### PR TITLE
Clarification regarding position ordering; fixed spelling mistakes.

### PR DESCRIPTION
**Pull request by indiedotkim**
Comment on start/end positions was initially wrong (due to copy & paste). Fixed now and added some further clarification in the comment. Fixed spelling mistakes.

### CODE REVIEW

**Comment by peterjc** [comment]
The typos and phrasing is improved, but I think the original meaning was correct.

**Comment by indiedotkim** [comment]
Hm. I think the phrasing is still not perfect, because I intended to say that the biological start/end are the way they are -- despite the numbers saying "the opposite".

**Comment by indiedotkim** [comment]
Is this clearer?

**Comment by peterjc** [comment]
Original:
*see the end is smaller than the begin*

i.e. numerically speaking, end < begin, or equivalently, begin > end.

@indiedotkim's current version is better, but quite long:
*Biological start position, which is located at a larger coordinate than the biological end position*

How about:
*Note biological start position numerically greater than end position*

(And similarly for the comment on the end position)

**Comment by indiedotkim** [comment]
Changed. My issue with the original version was that it repeated the statement for both positions and did not state the "biological" influence.

**Comment by peterjc** [comment]
I'm happy now (but would squash this down to one commit to keep the history simple).

@JervenBolleman?

**Comment by JervenBolleman** [comment]
Yes please squash into one commit, and peter you should be able to do the pull

**Comment by peterjc** [comment]
I'm happy to do it, but I don't have write permissions on this repo yet (just the paper).

**Comment by JervenBolleman** [comment]
Your both collaborators now

**Comment by peterjc** [comment]
Applied as single commit https://github.com/JervenBolleman/FALDO/commit/dbcbd7cc46d6a7e29bf7da5f64cc1435c1beed98 - closing. Thank you both.

**Comment by indiedotkim** [comment]
@peterjc @JervenBolleman Thank you both too!

I think I will continue with pull requests, so that we can continue having neatly logged and topically separated discussions. Otherwise we would have to use the issue tracker, which I find is a less favorable option. Opinions?

**Comment by peterjc** [comment]
If you've got concrete changes to suggest, pull requests are great.

If you've spotted something worth discussion then open an issue?

**Pull request closed without merging**
